name: Dreamscaper
favicon: null
layout_spectrum: 0.4584782072342932
typography_spectrum: 0.16775034624151886
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.4759636998642236
  lightness: 0.46338178194127977
  saturation: 0.852625320199877
  rhythmicContrast: 0.7823531294707209
purpose: []
